#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Backup the default Nginx configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Add custom header configuration to Nginx
sudo sed -i '/^server {/a \ \ \ \ add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
